report_header_info:
  - Pipeline version: v1.2.1
  - Contact E-mail: "qtl7@cdc.gov"
  - Project Type: "HMAS Application"
  - Sequencing Platform: "MiSeq High Output V3"
  - Sequencing Setup: "2x250"
  - Assay: ASY-SMNLA v1
  - Lot ID: 20268_ORP_21.O#

custom_logo: "step_mothur_logo.png"
custom_logo_url: "https://github.com/ncezid-biome/HMAS-QC-Pipeline2"
custom_logo_title: "Step-mothur"

software_versions:
  vsearch: "2.14.1"
  pear: "0.9.6"

section_comments:
  pear: "a tool to merge pair-end reads "
  qfilter: "a vsearch method (fastx_filter) to do quality filtering"
  dereplication: "a vsearch method (derep_fulllength) to group together duplicate reads"
  denoise: "a vsearch method (cluster_unoise) with UNOISE3 algorithm to perform denoising"
  cutadapt_trimmed_sequences_3: "`This includes the reverse compliment of the 3' primer and any read through sequence beyond that primer. 
  A normal Salmonella HMAS run will have varying sequence lengths trimmed 21-100 bp`"
  cutadapt_filtered_reads: "`Our HMAS data utilizes paired-end (PE) reads exclusively, rather than single-end (SE) reads`"

remove_sections:
  - fastqc_per_base_sequence_content
  - fastqc_sequence_duplication_levels
  - fastqc_status_checks
  - fastqc_top_overrepresented_sequences
  - fastqc_adapter_content
  - fastqc_sequence_length_distribution
  - fastqc_per_sequence_gc_content
  - fastqc_overrepresented_sequences

module_order:
  - fastqc
  - cutadapt
  - custom_content

custom_plot_config:
  primer_report:
    defaultsort:
      - column: "p_col1"
        direction: asc
  read_length_report:
    defaultsort:
      - column: "l_col1"
        direction: asc

custom_table_header_config:
  general_stats_table:
    total_sequences:
      format: "{:,.2f}"
    percent_duplicates:
      scale: "RdYlGn"

table_columns_visible:
  Cutadapt:
    percent_trimmed: False
  FastQC:
    avg_sequence_length: True
    percent_gc: False

read_count_multiplier: 0.001
read_count_prefix: "K"
read_count_desc: "thousands"


table_cond_formatting_rules:
  col1:
    fail:
      - lt: 30
      - s_contains: "n/a"
    warn:
      - lt: 49.99
    pass:
      - gt: 49.99
  col2:
    fail:
      - lt: 0.8
      - s_contains: "n/a"
    warn:
      - lt: 0.8999
    pass:
      - lt: 0.9799
    exe:
      - gt: 0.9799
  p_col1:
    fail:
      - lt: 30
      - s_contains: "n/a"
    warn:
      - lt: 49.99
    pass:
      - gt: 49.99

table_cond_formatting_colours:
  - exe: "#5bc0de"
  - pass: "#5cb85c"
  - warn: "#f0ad4e"
  - fail: "#d9534f"

report_section_order:
  hmas_run_report:
    order: 10
  read_length_report:
    order: 20
  primer_report:
    order: 30
  denoise:
    order: 40
  dereplication:
    order: 50
  qfilter:
    order: 60
  pear:
    order: 70



# top_modules:
#   - custom_content:
#   # - "hmas_run_report":


# show_analysis_paths: False
# show_analysis_time: False


# report_section_order:
#   hmas_run_report:
#     after: "pear"


# exclude_modules:
#   - general_stats